// Generated by evalforge fix — minimal zero-dependency flat ESLint config.
// No plugin imports (plugins may not be installed here) — core rules only.
// Extend freely once real lint tooling is installed in this target.
export default [
  {
    ignores: ["node_modules/**", "dist/**", ".next/**", "build/**"],
  },
  {
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "warn",
    },
  },
];
